hepsi : derle calistir

derle:
		g++ -I ./include/ -o ./lib/Islemler.o -c ./src/Islemler.cpp
		g++ -I ./include/ -o ./bin/EkranVeri.exe ./lib/Islemler.o ./src/main.cpp

calistir:
		./bin/EkranVeri.exe